FROM php:5.6-fpm

MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

ADD ./codeigniter.ini /usr/local/etc/php/conf.d
ADD ./codeigniter.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql

RUN usermod -u 1000 www-data

WORKDIR /var/www/codeigniter

CMD ["php-fpm"]

EXPOSE 9000
